document.addEventListener("DOMContentLoaded", () => {
  const app = document.getElementById("app");

  //Constants for the full story's word count slider.
  const WORD_MIN = 250;
  const WORD_MAX = 2000;
  const WORD_DEFAULT = 700;

  //state stores the information from each page.
  const state = {
    formData: null,                                  //Contains the data from the form in Step 1
    promptText: "",                                  //Stores the prompt editable in Step 2
    storyline: null,                                 //Stores the storyline returned by /api/storyline
    fairytaleText: "",                               //Stores the complete prose fairytale from Step 4
    narrationText: "",                               //Stores the narrative script for the shadow play generated in Step 6
    wordCount: WORD_DEFAULT,                         //Stores the selected target story length

    puppetPlan: null,                                //Stores the asset plan returned by /api/puppets/plan
    puppetImages: {},                                //Stores the images generated by ComfyUI

    comfyOnline: false,

    assetChoices: {},                                //Stores the most recent editable prompt for every character and background asset

    generationStatus: "",                            //Records if the generation is in progress
    isGenerating: false
  };

  // =====================================================
  // DOM HELPER FUNCTIONS
  // =====================================================

  //Function for constructing HTML elements more easily. Takes a tag name, an object of attributes, and an array of children elements.
  const el = (tag, attrs = {}, children = []) => {
    const node = document.createElement(tag);

    Object.entries(attrs).forEach(([k, v]) => {
      if (k === "class") node.className = v;
      else if (k === "text") node.textContent = v;
      else if (k === "html") node.innerHTML = v;
      else if (k.startsWith("on") && typeof v === "function") {
        node.addEventListener(k.slice(2), v);
      } else {
        node.setAttribute(k, v);
      }
    });

    children.forEach((c) => node.appendChild(c));

    return node;
  };

  //Creates a form field wrappert with a label and a control.
  const field = (labelText, control) =>
    el("div", { class: "field" }, [
      el("label", { text: labelText }),
      control
    ]);

  //Functions as the app's navigation mechanism.
  const setView = (node) => {
    app.innerHTML = "";
    app.appendChild(node);
    window.scrollTo(0, 0);
  };

  //Returns the application to its landing page.
  const goToLanding = () => {
    document.body.classList.add("landing-active");
    setView(viewLanding());
  };

  //Creates a home button that returns the user to the landing page.
  const createHomeButton = () => {
    const btn = el("div", {
      class: "home-button",
      title: "Back to home"
    });

    const img = el("img", {
      src: "home.png",
      alt: "Home"
    });

    btn.appendChild(img);
    btn.addEventListener("click", goToLanding);

    return btn;
  };

  //Displays a page and adds a home button to the document body.
  const setViewWithHome = (node) => {
    setView(node);
    const homeBtn = createHomeButton();
    document.body.appendChild(homeBtn);
  };


  // =====================================================
  // API HELPER FUNCTIONS
  // =====================================================

  //Helper function user for almoste all server requests. Sends a POST request and awaits/returns the JSON response.
  async function apiPost(path, payload) {
    const res = await fetch(path, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    });

    if (!res.ok) {
      const msg = await res.text().catch(() => "Unknown server error");
      throw new Error(msg || `Request failed: ${res.status}`);
    }

    return res.json();
  }

  // =====================================================
  // COMFY CHECK
  // =====================================================

  //Function to check if ComfyUI is reachable. Returns true if it is, and false if it is not.
  async function checkComfy() {
    try {
      const r = await fetch("/api/comfy/health");
      const data = await r.json();

      state.comfyOnline = !!data.ok;

      return state.comfyOnline;
    } catch {
      state.comfyOnline = false;
      return false;
    }
  }

  // =====================================================
  // COUNTRIES AND AGES
  // =====================================================

  //Array that contains all countries in the world, sorted alphabetically. 
  const countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
    "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia",
    "Comoros", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
    "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon",
    "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Côte d’Ivoire", "Jamaica", "Japan", "Jordan", "Kazakhstan",
    "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
    "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand",
    "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea",
    "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Republic of the Congo", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis",
    "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "São Tomé and Príncipe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
    "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka",
    "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago",
    "Tunisia", "Türkiye", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
    "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
  ].sort((a, b) =>
    a.localeCompare(b, "en")
  );

  //Array that contains the ages 6 through 10 as strings.
  const ages = Array.from({ length: 5 }, (_, i) => String(i + 6));

  //Function that creates a dropdown menu with a given id, an array of options, and a placeholder.
  const makeSelect = (id, options, placeholder = "Select...") => {
    const s = el("select", {
      id,
      name: id
    });

    s.appendChild(
      el("option", {
        value: "",
        text: placeholder
      })
    );

    options.forEach((o) =>
      s.appendChild(
        el("option", {
          value: o,
          text: o
        })
      )
    );

    return s;
  };

  // =====================================================
  // PROMPT BUILDER FUNCTION
  // =====================================================

  //Receives the form data from Step 1 and builds a prompt string for the storyline generation. It does not contact the server yet.
  const buildPromptFromForm = (d) => {
    const names = (d.names || "").trim();
    const mainCharacterName = (d.mainCharacterName || "").trim();

    const namesLine = names
      ? `Preferred character names: ${names}`
      : `Preferred character names: none`;

    return [
      "You are a children's fairytale writer and story designer.",
      "Write a structured storyline divided into acts suitable for a child.",
      "",
      "Constraints:",
      `- Subtly include cultural elements from ${d.nationality} in the story`,
      `- Child age: ${d.age}`,
      `- Main character name: ${mainCharacterName || "(not specified)"}`,
      `- Moral of the story: ${d.moral}`,
      `- Themes: ${d.themes || "(none)"}`,
      `- Main character characteristics: ${d.characteristics || "(not specified)"}`,
      `- Fantastical elements: ${d.fantastical || "(not specified)"}`,
      `- ${namesLine}`,
      "",
      "Output requirements:",
      "- Provide a short logline.",
      "- Provide EXACTLY 5 acts.",
      "- Each act must contain:",
      "  - title",
      "  - summary",
      "  - beats",
      "",
      "- Keep it age-appropriate."
    ].join("\n");
  };

  // =====================================================
  // LANDING SCREEN
  // =====================================================

  //Function that creates and returns the landing screen interface.
  function viewLanding() {
    const startBtn = el("button", {
      class: "landing-screen__start",
      text: "Start my story"
    });

    startBtn.addEventListener("click", () => {
      document.body.classList.remove("landing-active");
      setViewWithHome(viewStep1());
    });

    return el("div", { class: "landing-screen" }, [
      el("div", { class: "landing-screen__content" }, [
        el("div", { class: "landing-screen__copy" }, [
          el("div", {
            class: "landing-screen__eyebrow",
            text: "Welcome to Generating Shadows"
          }),
          el("h1", {
            text: "A magical story builder for puppet theatre"
          }),
          el("p", {
            text: "Create your own fairytale, generate characters and backgrounds, and bring your shadow play story to life. Start here to begin your experience."
          }),
          startBtn
        ])
      ])
    ]);
  }

  // =====================================================
  // STEP 1
  // =====================================================

  //Creates the form for the story building.
  function viewStep1() {
    const moral = el("input", {
      type: "text"
    });

    const characteristics = el("textarea");                   //Creates an input field for the main character's characteristics.
    const fantastical = el("textarea");                       //Creates an input field for the fantastical elements of the story.

    const nationality = makeSelect(                           //Creates the dropdown menu for the countries.
      "nationality",
      countries,
      "Select a country"
    );

    const age = makeSelect(                                   //Creates the dropdown menu for the ages.
      "age",
      ages,
      "Select age"
    );

    const mainCharacterName = el("input", {                   //Creates the input field for the main character's name.
      type: "text",
      placeholder: "e.g. Olivia"
    });

    const names = el("input", {                               //Creates the input field for the preferred character names.
      type: "text",
      placeholder: "e.g. Mia, Leo"
    });

    const themes = el("input", {                              //Creates the input field for the themes of the story.
      type: "text"
    });

    //CReates a real HTML form element with all the above fields and a submit button.
    const form = el("form", {}, [
      el("h1", {
        text: "Step 1 — Story Inputs"
      }),

      el("div", { class: "section-grid" }, [
        el("div", { class: "section-column" }, [
          el("section", { class: "form-section" }, [
            el("h2", { text: "Child's Profile" }),
            field("Child nationality", nationality),
            field("Child age", age)
          ]),

          el("section", { class: "form-section" }, [
            el("h2", { text: "Plot" }),
            field("Choose the moral of the story", moral),
            field("Themes", themes)
          ])
        ]),

        el("div", { class: "section-column" }, [
          el("section", { class: "form-section" }, [
            el("h2", { text: "Characters" }),
            field("Main character name", mainCharacterName),
            field("Preferred character names", names),
            field("Characteristics for the main character", characteristics),
            field("Fantastical elements", fantastical)
          ])
        ])
      ]),

      el("div", { class: "actions" }, [
        el("button", {
          type: "submit",
          class: "next-top primary-button",
          text: "Next →"
        })
      ])
    ]);

    form.addEventListener("submit", (e) => {
      e.preventDefault();

      const d = {
        moral: moral.value.trim(),
        characteristics: characteristics.value.trim(),
        fantastical: fantastical.value.trim(),
        nationality: nationality.value,
        age: age.value,
        mainCharacterName: mainCharacterName.value.trim(),
        names: names.value.trim(),
        themes: themes.value.trim()
      };

      if (!d.moral || !d.nationality || !d.age) {
        alert("Please fill Moral, Nationality, and Age.");
        return;
      }

      state.formData = d;                                                    //Stores the data from the form in the state object.
      state.promptText = buildPromptFromForm(d);                             //Builds the prompt from the form data and stores it in the state object.

      setViewWithHome(viewStep2());                                          //Constructs and displays the next page (Step 2).
    });

    return el("div", { class: "step1-page" }, [
      el("div", { class: "card" }, [form])
    ]);
  }

  // =====================================================
  // STEP 2
  // =====================================================

  //Creates the interface for Step 2, where the user can edit the prompt before generating the storyline.
  function viewStep2() {
    const promptBox = el("textarea", {                                      //Creates a 16 row text area for the user to edit the prompt
      class: "mono prompt-editor",
      rows: 16
    });

    promptBox.value = state.promptText;                                     //Places the prompt inside the text area for the user to edit.

    const status = el("div", {
      class: "small"
    });

    const nextBtn = el("button", {                                          //Creates a button that will generate the storyline when clicked.
      class: "next-top primary-button",
      text: "Next → Generate Storyline"
    });

    nextBtn.addEventListener("click", async () => {
      try {
        nextBtn.disabled = true;
        status.textContent = "Generating storyline with OpenAI…";

        state.promptText = promptBox.value;                                 //The user may have altered the prompt, so the current text area value replaces the original prompt.

        state.storyline = await apiPost("/api/storyline", {                 //Sneds the prompt to the server to generate the storyline.
          prompt: state.promptText
        });

        setViewWithHome(viewStep3());
      } catch (err) {
        alert(err.message);
      } finally {
        nextBtn.disabled = false;
        status.textContent = "";
      }
    });

    return el("div", { class: "step1-page" }, [
      el("div", { class: "card" }, [
        el("h1", {
          text: "Step 2 — Edit Prompt"
        }),

        field("Prompt", promptBox),

        el("div", { class: "actions" }, [
          el("button", {
            class: "back-button primary-button",
            type: "button",
            text: "← Back",
            onclick: () => setViewWithHome(viewStep1())
          }),

          nextBtn
        ]),

        status
      ])
    ]);
  }

  // =====================================================
  // STEP 3
  // =====================================================

  //Function that creates the interface for Step 3, where the user can edit the generated storyline.
  function viewStep3() {
    const status = el("div", { class: "small" });

    const loglineBox = el("textarea", { class: "mono" });
    loglineBox.value = state.storyline?.logline || "";

    // Prepares UI controls for each act and stores on the act object
    state.storyline.acts.forEach((act) => {
      if (!act._ui) {
        const title = el("input", { type: "text" });
        title.value = act.title || "";

        const summary = el("textarea");
        summary.value = act.summary || "";

        const beats = el("textarea", { class: "mono" });
        beats.value = (act.beats || []).join("\n");

        act._ui = { title, summary, beats };
      }
    });

    function syncEdits() {
      state.storyline.logline = loglineBox.value.trim();

      state.storyline.acts.forEach((act) => {
        const ui = act._ui;
        act.title = ui.title.value.trim();
        act.summary = ui.summary.value.trim();
        act.beats = ui.beats.value
          .split("\n")
          .map((s) => s.trim())
          .filter(Boolean);
      });
    }

    //Creates the tabs for the logline and each act, and the content area where the user can edit the log line and each act's details. 
    const tabs = el("div", { class: "tabs" });
    const contentArea = el("div", { class: "tab-content" });

    let activeTab = 0; // 0 = logline, 1..n = acts

    // Switches the active tab and refreshes the visible content.
    function setActiveTab(i) {
      activeTab = i;
      Array.from(tabs.children).forEach((b, idx) => {
        if (idx === i) b.classList.add("active");
        else b.classList.remove("active");
      });
      renderActive();
    }

    //Renders the selected tab's content
    function renderActive() {
      contentArea.innerHTML = "";                                   //Removes the previously visible tab content

      if (activeTab === 0) {
        contentArea.appendChild(field("Logline", loglineBox));
        return;
      }

      const actIndex = activeTab - 1;
      const act = state.storyline.acts[actIndex];
      const ui = act._ui;

      contentArea.appendChild(el("hr"));

      contentArea.appendChild(field("Title", ui.title));
      contentArea.appendChild(field("Summary", ui.summary));
      contentArea.appendChild(field("Beats", ui.beats));

      const regen = el("button", {
        class: "secondary primary-button",
        type: "button",
        text: "Regenerate this act"
      });

      regen.addEventListener("click", async () => {                 //Starts the act regeneration
        try {
          regen.disabled = true;
          status.textContent = `Regenerating Act ${actIndex + 1}…`;

          syncEdits();

          const updated = await apiPost("/api/act/regenerate", {
            prompt: state.promptText,
            storyline: state.storyline,
            actIndex
          });

          state.storyline.acts[actIndex] = updated.act;            //Replaces only the selected act with the newly generated one

          const a = state.storyline.acts[actIndex];                //Rebuilds the act's UI
          a._ui = null;

          if (!a._ui) {                                            //Re-prepares UI controls
            const title = el("input", { type: "text" });
            title.value = a.title || "";

            const summary = el("textarea");
            summary.value = a.summary || "";

            const beats = el("textarea", { class: "mono" });
            beats.value = (a.beats || []).join("\n");

            a._ui = { title, summary, beats };
          }

          renderTabs();
          setActiveTab(activeTab);
        } catch (e) {
          alert(e.message);
        } finally {
          regen.disabled = false;
          status.textContent = "";
        }
      });

      contentArea.appendChild(el("div", { class: "actions" }, [regen]));
    }


    function renderTabs() {
      tabs.innerHTML = "";
      const logBtn = el("button", { class: "tab-button", type: "button", text: "Logline" });
      logBtn.addEventListener("click", () => setActiveTab(0));
      tabs.appendChild(logBtn);

      state.storyline.acts.forEach((act, idx) => {
        const b = el("button", { class: "tab-button", type: "button", text: `Act ${idx + 1}` });
        b.addEventListener("click", () => setActiveTab(idx + 1));
        tabs.appendChild(b);
      });

      //Set initial active
      setActiveTab(activeTab);
    }

    const nextBtn = el("button", { class: "next-top primary-button", text: "Next → Generate Full Fairytale" });

    //Calls POST /api/fairytale with the prompt, the storyline and the current default word count to generate the full story in prose
    nextBtn.addEventListener("click", async () => {
      try {
        nextBtn.disabled = true;
        status.textContent = "Generating fairytale with OpenAI…";

        syncEdits();

        const data = await apiPost("/api/fairytale", {
          prompt: state.promptText,
          storyline: state.storyline,
          wordCount: state.wordCount
        });

        state.fairytaleText = data.text || "";

        //Displays the Step 4 interface
        setViewWithHome(viewStep4());
      } catch (e) {
        alert(e.message);
      } finally {
        nextBtn.disabled = false;
        status.textContent = "";
      }
    });

    renderTabs();

    return el("div", { class: "step1-page" }, [
      el("div", { class: "card" }, [
        el("h1", { text: "Step 3 — Edit Storyline" }),

        tabs,
        contentArea,

        el("div", { class: "actions" }, [
          el("button", { class: "back-button primary-button", type: "button", text: "← Back", onclick: () => setViewWithHome(viewStep2()) }),

          nextBtn
        ]),

        status
      ])
    ]);
  }

  // =====================================================
  // STEP 4
  // =====================================================

  // Creates the Step 4 interface for editing the full fairytale.
  function viewStep4() {
    const status = el("div", {
      class: "small"
    });

    const taleArea = el("textarea", {                                        //Creates the full-story text area
      class: "mono story-editor"
    });

    taleArea.value = state.fairytaleText || "";                              //Loads the generated fairy tale

    //Creates the target words slider from 250 to 2000 in increments of 50
    const slider = el("input", {
      type: "range",
      min: WORD_MIN,
      max: WORD_MAX,
      step: 50,
      value: state.wordCount
    });

    const sliderValue = el("div", {
      class: "sliderValue mono",
      text: `${state.wordCount} words`
    });

    slider.addEventListener("input", () => {
      state.wordCount = Number(slider.value);
      sliderValue.textContent =
        `${state.wordCount} words`;

    });

    //Creates the regenerate button. The button calls POST /api/fairytale and regenerates the story based on the initial prompt, the storyline and the wordcount.
    const regenBtn = el("button", {
      class: "secondary primary-button",
      type: "button",
      text: "Regenerate full fairytale"
    });

    regenBtn.addEventListener("click", async () => {
      try {
        regenBtn.disabled = true;
        status.textContent = "Regenerating fairytale with OpenAI…";

        const data = await apiPost("/api/fairytale", {
          prompt: state.promptText,
          storyline: state.storyline,
          wordCount: state.wordCount
        });

        state.fairytaleText = data.text || "";
        taleArea.value = state.fairytaleText;
      } catch (e) {
        alert(e.message);
      } finally {
        regenBtn.disabled = false;
        status.textContent = "";
      }
    });

    //Creates the next button. It calls POST /api/puppets/plan and the server returns a plan of backgrounds and characters. The application the enters Step 5a.
    const nextBtn = el("button", {
      class: "next-top primary-button",
      text: "Next → Prepare Assets"
    });

    nextBtn.addEventListener("click", async () => {
      try {
        nextBtn.disabled = true;
        status.textContent = "Creating asset plan…";

        state.fairytaleText = taleArea.value;                              //Saves manual story edits

        const plan = await apiPost("/api/puppets/plan", {
          storyline: state.storyline,
          fairytaleText: state.fairytaleText
        });

        state.puppetPlan = plan;

        setViewWithHome(viewStep5aReview());                              //Sends the application to the Step 5a page
      } catch (e) {
        alert(e.message);
      } finally {
        nextBtn.disabled = false;
        status.textContent = "";
      }
    });

    return el("div", { class: "step1-page" }, [
      el("div", { class: "card" }, [

        el("h1", {
          text: "Step 4 — Full Fairytale"
        }),

        el("div", { class: "field" }, [
          el("label", {
            text: "Target story length"
          }),
          el("div", {
            class: "sliderWrap"
          }, [
            slider,
            sliderValue
          ])
        ]),

        el("div", {
          class: "story-toolbar"
        }, [
          regenBtn
        ]),

        field("Story", taleArea),

        el("div", {
          class: "actions"
        }, [

          el("button", {
            class: "back-button primary-button",
            type: "button",
            text: "← Back",
            onclick: () => setViewWithHome(viewStep3())
          })

        ]),

        nextBtn,

        status
      ])
    ]);
  }

  // =====================================================
  // ASSET HELPER FUNCTIONS
  // =====================================================

  //Collects background assets grouped by their key from the puppet plan.
  function getBackgroundAssets() {
    const backgroundMap = new Map();

    for (const act of state.puppetPlan?.acts || []) {
      const bg = act.background;

      if (!bg?.key) continue;

      if (!backgroundMap.has(bg.key)) {
        backgroundMap.set(bg.key, {
          kind: "background",
          key: bg.key,
          title: bg.key,
          prompt: bg.prompt || "",
          acts: []
        });
      }

      backgroundMap.get(bg.key).acts.push({
        actIndex: act.actIndex,
        actTitle: act.actTitle
      });
    }

    return [...backgroundMap.values()].map((bg) => ({
      ...bg,
      title:
        bg.acts.length === 1
          ? `Background — Act ${bg.acts[0].actIndex + 1}`
          : `Background — Acts ${bg.acts
            .map((a) => a.actIndex + 1)
            .join(", ")}`
    }));
  }

  //Collects character assets grouped by their key from the puppet plan.
  function getCharacterAssets() {
    const charactersMap = new Map();

    for (const act of state.puppetPlan?.acts || []) {
      for (const ch of act.characters || []) {
        if (!ch?.key) continue;

        if (!charactersMap.has(ch.key)) {
          charactersMap.set(ch.key, {
            kind: "character",
            key: ch.key,
            title: ch.name || ch.key,
            name: ch.name || ch.key,
            prompt: ch.prompt || "",
            acts: []
          });
        }

        charactersMap.get(ch.key).acts.push({
          actIndex: act.actIndex,
          actTitle: act.actTitle
        });
      }
    }

    return [...charactersMap.values()];
  }

  //Returns one array containing backgrounds first and characters second.
  function getAllAssets() {
    return [
      ...getBackgroundAssets(),
      ...getCharacterAssets()
    ];
  }

  // Ensures each asset from the current plan has a default editable prompt state.
  function ensureAssetChoices() {
    for (const asset of getAllAssets()) {
      if (!state.assetChoices[asset.key]) {
        state.assetChoices[asset.key] = {
          promptText: asset.prompt || ""
        };
      }
    }
  }

  // =====================================================
  // SVG HELPER AND EDITING FUNCTIONS
  // =====================================================

  //Converts raw SVG XML into a browser loadable data URL
  function svgTextToBrowserDataUrl(
    svgText
  ) {
    return (
      "data:image/svg+xml;charset=utf-8," +
      encodeURIComponent(svgText)
    );
  }

  // Parses a string of SVG markup and validates that it contains a real SVG document.
  function parseSvg(svgText) {
    //Creates a browser XML parser
    const parser =
      new DOMParser();

    //Converts the SVG text into a DOM document
    const documentNode =
      parser.parseFromString(
        svgText,
        "image/svg+xml"
      );

    //Throws an error if a <parseerror> element is detected
    const parserError =
      documentNode.querySelector(
        "parsererror"
      );

    if (parserError) {
      throw new Error(
        "The generated SVG could not be parsed."
      );
    }

    const svg =
      documentNode.documentElement;

    //Ensures the content has <svg> as its root
    if (
      !svg ||
      svg.tagName
        .toLowerCase() !== "svg"
    ) {
      throw new Error(
        "The generated content is not a valid SVG."
      );
    }

    return {
      documentNode,
      svg
    };
  }

  //Does the reverse of parseSvg(), converting a modified SVG DOM element back into SVG text.
  function serializeSvg(svg) {
    return new XMLSerializer()
      .serializeToString(svg);
  }

  //Downloads an SVG string as a file
  function downloadSvgText(
    svgText,
    filename
  ) {
    const blob =
      new Blob(
        [svgText],
        {
          type:
            "image/svg+xml;charset=utf-8"
        }
      );

    const url =                                           //Creates a temporary browser URL for the Blob
      URL.createObjectURL(blob);

    const link =
      document.createElement("a");

    link.href = url;
    link.download = filename;

    document.body.appendChild(
      link
    );

    link.click();
    link.remove();

    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 1000);
  }

  //Creates a filename safe identifier
  function makeSafeFilename(text) {
    return String(
      text || "asset"
    )
      .toLowerCase()
      .trim()
      .replace(
        /[^a-z0-9]+/g,
        "-"
      )
      .replace(
        /^-+|-+$/g,
        ""
      );
  }

  // Reads the SVG viewBox or fallback dimensions so the element can be positioned and scaled correctly.
  function getSvgViewBox(svg) {
    const viewBox =
      svg.viewBox?.baseVal;

    if (
      viewBox &&
      viewBox.width > 0 &&
      viewBox.height > 0
    ) {
      return {
        x:
          viewBox.x,

        y:
          viewBox.y,

        width:
          viewBox.width,

        height:
          viewBox.height
      };
    }

    const width =
      Number.parseFloat(
        svg.getAttribute(
          "width"
        )
      );

    const height =
      Number.parseFloat(
        svg.getAttribute(
          "height"
        )
      );

    if (
      Number.isFinite(width) &&
      width > 0 &&
      Number.isFinite(height) &&
      height > 0
    ) {
      return {
        x: 0,
        y: 0,
        width,
        height
      };
    }

    throw new Error(
      "The SVG has no valid viewBox or dimensions."
    );
  }

  // Mounts an SVG in an offscreen container so its dimensions can be measured safely.
  function mountSvgForMeasurement(
    svg
  ) {
    const container =
      document.createElement("div");

    container.style.position =
      "fixed";

    container.style.left =
      "-100000px";

    container.style.top =
      "-100000px";

    container.style.width =
      "2000px";

    container.style.height =
      "2000px";

    container.style.visibility =
      "hidden";

    container.style.pointerEvents =
      "none";

    document.body.appendChild(
      container
    );

    const importedSvg =
      document.importNode(
        svg,
        true
      );

    container.appendChild(
      importedSvg
    );

    return {
      container,
      svg:
        importedSvg
    };
  }

  //This function performs a geometric Boolean union between the character silhouette and the pedestal, turning them into one unified black vector shape.
  function weldCharacterAndPedestalForExport(
    svg
  ) {
    if (!window.paper) {
      throw new Error(
        "Paper.js was not loaded. Check the Paper.js script tag in index.html."                //Function depends on Paper.js being loaded in index.html
      );
    }

    const figure =
      svg.querySelector(
        "#character-figure"
      );

    const pedestal =
      svg.querySelector(
        "#character-pedestal"
      );

    if (!figure) {
      throw new Error(
        "The character figure could not be found before welding."
      );
    }

    if (!pedestal) {
      throw new Error(
        "The character pedestal could not be found before welding."
      );
    }

    const paperScope =
      new paper.PaperScope();

    const canvas =
      document.createElement(
        "canvas"
      );

    canvas.width = 1;
    canvas.height = 1;

    paperScope.setup(
      canvas
    );

    try {
      const sourceGroup =
        svg.ownerDocument
          .createElementNS(
            "http://www.w3.org/2000/svg",
            "g"
          );

      sourceGroup.appendChild(
        figure.cloneNode(true)
      );

      sourceGroup.appendChild(
        pedestal.cloneNode(true)
      );

      const imported =
        paperScope.project.importSVG(
          sourceGroup,
          {
            expandShapes: true,
            applyMatrix: true,
            insert: true
          }
        );

      const pathItems =
        imported.getItems({
          recursive: true,

          match: (item) => {
            const isPathItem =
              item instanceof
              paperScope.Path ||
              item instanceof
              paperScope.CompoundPath;

            const isCompoundChild =
              item.parent instanceof
              paperScope.CompoundPath;

            return (
              isPathItem &&
              !isCompoundChild
            );
          }
        });

      if (
        pathItems.length === 0
      ) {
        throw new Error(
          "No vector paths were found in the character SVG."
        );
      }

      let combined =
        pathItems[0];

      for (
        let index = 1;
        index < pathItems.length;
        index += 1
      ) {
        combined =
          combined.unite(
            pathItems[index],
            {
              insert: false
            }
          );
      }

      combined.fillColor =
        new paperScope.Color(
          "#000000"
        );

      combined.strokeColor =
        null;

      combined.name =
        "character-cut-shape";

      const exportedNode =
        combined.exportSVG({
          asString: false,
          matchShapes: false,
          reduceAttributes: false
        });

      exportedNode.setAttribute(
        "id",
        "character-cut-shape"
      );

      exportedNode.setAttribute(
        "fill",
        "#000000"
      );

      exportedNode.setAttribute(
        "stroke",
        "none"
      );

      figure.remove();
      pedestal.remove();

      const finalNode =
        svg.ownerDocument.importNode(
          exportedNode,
          true
        );

      svg.appendChild(
        finalNode
      );

      return svg;

    } finally {
      paperScope.project.clear();
    }
  }

  // Adds a pedestal beneath the character figure in the SVG and prepares it for export.
  async function addCharacterPedestalToSvg(
    svgText
  ) {
    const {
      svg
    } = parseSvg(
      svgText
    );

    if (
      svg.querySelector(
        "#character-pedestal"
      )
    ) {
      const unchanged =
        serializeSvg(svg);

      return {
        svgText:
          unchanged,

        dataUrl:
          svgTextToBrowserDataUrl(
            unchanged
          )
      };
    }

    const measurement =
      mountSvgForMeasurement(
        svg
      );

    try {
      const measuredSvg =
        measurement.svg;

      const viewBox =
        getSvgViewBox(
          measuredSvg
        );

      const figureGroup =
        measuredSvg.ownerDocument
          .createElementNS(
            "http://www.w3.org/2000/svg",
            "g"
          );

      figureGroup.setAttribute(
        "id",
        "character-figure"
      );

      const children =
        Array.from(
          measuredSvg.children
        );

      children.forEach(
        (child) => {
          const tag =
            child.tagName
              .toLowerCase();

          if (
            tag === "defs" ||
            tag === "metadata" ||
            tag === "title" ||
            tag === "desc"
          ) {
            return;
          }

          figureGroup.appendChild(
            child
          );
        }
      );

      measuredSvg.appendChild(
        figureGroup
      );

      const figureBounds =
        figureGroup.getBBox();

      if (
        figureBounds.width <= 0 ||
        figureBounds.height <= 0
      ) {
        throw new Error(
          "The character SVG contains no measurable figure."
        );
      }

      const pedestalWidth =                           //25% of original canvas
        viewBox.width * 0.25;

      const pedestalHeight =                          //height = 18% of original canvas
        viewBox.height * 0.18;

      const pedestalX =
        figureBounds.x +
        figureBounds.width / 2 -
        pedestalWidth / 2;

      const overlap =                                //The slight overlap makes sure the figure connects to the pedestal
        viewBox.height * 0.03;

      const figureBottom =
        figureBounds.y +
        figureBounds.height;

      const pedestalY =
        figureBottom -
        overlap;

      const pedestal =
        measuredSvg.ownerDocument
          .createElementNS(
            "http://www.w3.org/2000/svg",
            "rect"
          );

      pedestal.setAttribute(
        "id",
        "character-pedestal"
      );

      pedestal.setAttribute(
        "x",
        String(pedestalX)
      );

      pedestal.setAttribute(
        "y",
        String(pedestalY)
      );

      pedestal.setAttribute(
        "width",
        String(pedestalWidth)
      );

      pedestal.setAttribute(
        "height",
        String(pedestalHeight)
      );

      pedestal.setAttribute(
        "rx",
        String(
          pedestalHeight / 5
        )
      );

      pedestal.setAttribute(
        "ry",
        String(
          pedestalHeight / 5
        )
      );

      pedestal.setAttribute(
        "fill",
        "#000000"
      );

      measuredSvg.insertBefore(
        pedestal,
        figureGroup
      );

      const padding =
        viewBox.height * 0.015;

      const minX =
        Math.min(
          viewBox.x,
          pedestalX - padding
        );

      const minY =
        Math.min(
          viewBox.y,
          figureBounds.y - padding
        );

      const maxX =
        Math.max(
          viewBox.x +
          viewBox.width,

          pedestalX +
          pedestalWidth +
          padding
        );

      const maxY =
        Math.max(
          viewBox.y +
          viewBox.height,

          pedestalY +
          pedestalHeight +
          padding
        );

      measuredSvg.setAttribute(
        "viewBox",
        [
          minX,
          minY,
          maxX - minX,
          maxY - minY
        ].join(" ")
      );

      measuredSvg.removeAttribute(
        "width"
      );

      measuredSvg.removeAttribute(
        "height"
      );

      const finalSvgText =
        serializeSvg(
          measuredSvg
        );

      return {
        svgText:
          finalSvgText,

        dataUrl:
          svgTextToBrowserDataUrl(
            finalSvgText
          )
      };

    } finally {
      measurement.container.remove();
    }
  }


  // Generates an asset image for the given asset definition and prepares it for display.
  async function generateAsset(
    asset,
    options = {}
  ) {
    const {
      force = false
    } = options;

    const choice =
      state.assetChoices[
      asset.key
      ];

    if (!choice) {
      throw new Error(
        "Missing asset choice state."
      );
    }

    const img =
      await apiPost(
        "/api/puppets/image",
        {
          kind: asset.kind,

          key: asset.key,

          prompt:
            choice.promptText ||
            asset.prompt ||
            "",

          force
        }
      );

    if (
      asset.kind === "character" &&
      img?.svgText
    ) {
      const characterSvg =
        await addCharacterPedestalToSvg(
          img.svgText
        );

      img.svgText =
        characterSvg.svgText;

      img.dataUrl =
        characterSvg.dataUrl;
    }

    state.puppetImages[
      asset.key
    ] = img;
  }

  // =====================================================
  // STEP 5A
  // =====================================================

  // Creates the Step 5a interface for inspecting and editing generated asset prompts.
  function viewStep5aReview() {
    //Ensures every asset has an editable state prompt.
    ensureAssetChoices();

    //Creates the two lists used by the tabs
    const backgroundAssets = getBackgroundAssets();
    const characterAssets = getCharacterAssets();

    const status = el("div", {
      class: "small"
    });

    const list = el("div", {
      class: "asset-list"
    });


    //Creates the tabs
    let currentView = "backgrounds";

    const tabs = el("div", {
      class: "tabs"
    });

    const bgTab = el("button", {
      class: "tab-button active",
      type: "button",
      text: "Backgrounds"
    });

    const charTab = el("button", {
      class: "tab-button",
      type: "button",
      text: "Characters"
    });

    tabs.appendChild(bgTab);
    tabs.appendChild(charTab);

    //Renders the editable prompt editor for a single asset card.
    const renderAssetPrompt = (asset) => {
      const choice = state.assetChoices[asset.key];

      if (!choice.promptText)                                          //Restores the original prompt if the current prompt is empty.
        choice.promptText = asset.prompt || "";

      const promptArea = el("textarea", {
        class: "mono"
      });

      promptArea.value = choice.promptText;                            //Displays the prompt

      promptArea.addEventListener("input", () => {                     //Immediately saves every change
        choice.promptText = promptArea.value;
      });

      return el("section", {
        class: "form-section"
      }, [

        el("h2", {
          text: asset.title
        }),

        asset.acts?.length
          ? el("div", {
            class: "small",
            text:
              `Used in: ${asset.acts
                .map(a => `Act ${a.actIndex + 1}`)
                .join(", ")}`
          })
          : el("div"),

        field(
          asset.kind === "background"
            ? "Background Prompt"
            : "Character Description",
          promptArea
        )

      ]);

    };


    // Renders the currently selected asset list for the active tab.
    function renderAssets() {
      list.innerHTML = "";

      const assets =
        currentView === "backgrounds"
          ? backgroundAssets
          : characterAssets;

      assets.forEach(asset => {
        list.appendChild(
          renderAssetPrompt(asset)
        );
      });

    }

    bgTab.addEventListener("click", () => {

      currentView = "backgrounds";

      bgTab.classList.add("active");
      charTab.classList.remove("active");

      renderAssets();

    });

    charTab.addEventListener("click", () => {

      currentView = "characters";

      charTab.classList.add("active");
      bgTab.classList.remove("active");

      renderAssets();

    });

    renderAssets();


    //Creates the next button, which gather all assets for generation and navigates to Step 5b with a starting message.
    const nextBtn = el("button", {
      class: "next-top primary-button",
      text: "Next → Generate Assets"
    });

    nextBtn.addEventListener("click", async () => {

      const assets = getAllAssets();

      try {

        nextBtn.disabled = true;

        state.isGenerating = true;

        setView(viewStep5bDisplay("Starting generation…"));

        for (const asset of assets) {                            //Generates assets one at a time

          state.generationStatus =
            `Generating ${asset.title}…`;

          setViewWithHome(
            viewStep5bDisplay(                                  //Switches to the Step 5b interface
              state.generationStatus
            )
          );

          await generateAsset(asset);

          state.generationStatus =
            `Generated ${asset.title}`;

          setViewWithHome(
            viewStep5bDisplay(
              state.generationStatus
            )
          );

        }

        state.generationStatus =
          "Generation complete.";

        state.isGenerating = false;

        setViewWithHome(
          viewStep5bDisplay(
            state.generationStatus
          )
        );

      } catch (e) {

        console.error(e);

        state.isGenerating = false;

        state.generationStatus =
          "Generation failed.";

        setViewWithHome(
          viewStep5bDisplay(
            state.generationStatus
          )
        );

        alert(e.message || e);

      }

    });

    //Page construction
    return el("div", {
      class: "step1-page"
    }, [

      el("div", {
        class: "card"
      }, [

        el("h1", {
          text: "Step 5a — Review Asset Descriptions"
        }),

        el("div", {
          class: "small",
          text:
            "Review and edit the descriptions that will be used to generate your backgrounds and characters before generating the artwork."
        }),

        tabs,

        list,

        el("div", {
          class: "actions"
        }, [

          el("button", {
            class: "back-button primary-button",
            type: "button",
            text: "← Back",
            onclick: () =>
              setViewWithHome(viewStep4())
          })

        ]),

        nextBtn,

        status

      ])
    ]);
  }

  // =====================================================
  // STEP 5B
  // =====================================================

  // Renders the asset generation review screen for Step 5b, showing background and character assets with status and tabs.
  function viewStep5bDisplay(message = "") {
    const backgroundAssets = getBackgroundAssets();
    const characterAssets = getCharacterAssets();

    let currentView = "backgrounds";

    // Show the current generation status message above the asset views.
    const status = el("div", {
      id: "generation-status",
      class: "small",
      text: message || state.generationStatus || ""
    });

    const tabs = el("div", {
      class: "tabs"
    });

    const bgTab = el("button", {
      class: "tab-button active",
      type: "button",
      text: "Backgrounds"
    });

    const charTab = el("button", {
      class: "tab-button",
      type: "button",
      text: "Characters"
    });

    const assetGrid = el("div", {
      class: "assetGrid"
    });

    tabs.appendChild(bgTab);
    tabs.appendChild(charTab);

    // Build the UI for one asset card, including preview, prompt editing, and regeneration controls.
    function renderAssetCard(asset) {
      const imageContainer = el("div", {
        class: "asset-image"
      });

      function refreshImage() {

        imageContainer.innerHTML = "";

        const generated =
          state.puppetImages[asset.key];

        if (generated?.dataUrl) {

          imageContainer.appendChild(

            el("img", {
              src: generated.dataUrl,
              alt: asset.title
            })

          );

        } else {

          const loading = el("div", {
            class: "loading-placeholder"
          }, [

            el("div", {
              class: "loading-stars",
              text: "✨"
            }),

            el("div", {
              class: "loading-text",
              text: "Generating illustration..."
            }),

            el("div", {
              class: "loading-bar"
            })

          ]);

          imageContainer.appendChild(loading);

        }

      }


      refreshImage();

      const choice = state.assetChoices[asset.key];

      if (!choice.promptText)
        choice.promptText = asset.prompt || "";

      //Lets the user adjust the prompt text for this specific asset.
      const promptArea = el("textarea", {
        class: "asset-prompt-editor"
      });

      promptArea.value = choice.promptText;

      promptArea.addEventListener("input", () => {
        choice.promptText = promptArea.value;
      });

      const promptSection = el("div", {
        class: "prompt-section hidden"
      }, [

        el("label", {
          text:
            asset.kind === "background"
              ? "Background Prompt"
              : "Character Description"
        }),

        promptArea

      ]);

      let expanded = false;

      const togglePrompt = el("button", {
        class: "secondary primary-button asset-action-button edit-prompt-button",
        type: "button",
        text: "Edit Prompt ▼"

      });

      togglePrompt.addEventListener("click", () => {

        expanded = !expanded;

        promptSection.classList.toggle(
          "hidden",
          !expanded
        );

        togglePrompt.textContent =
          expanded
            ? "Hide Prompt ▲"
            : "Edit Prompt ▼";

      });

      // Regenerates the current asset image when the user requests it.
      const regenerateButton = el("button", {
        class: "secondary primary-button asset-action-button",
        type: "button",
        text: "Regenerate"
      });

      regenerateButton.addEventListener(
        "click",
        async () => {

          try {
            regenerateButton.disabled = true;
            delete state.puppetImages[asset.key];
            refreshImage();

            await generateAsset(asset, {
              force: true
            });

            refreshImage();


          }
          catch (err) {

            console.error(err);

            alert(err.message);

          }
          finally {

            regenerateButton.disabled = false;

          }

        }
      );

      const card = el("div", {

        class: `asset-card ${asset.kind === "background"
          ? "background-asset-card"
          : "character-asset-card"
          }`
      }, [

        el("h3", {
          text: asset.title
        }),

        el("div", {
          class: "small",
          text:
            "Used in: " +
            asset.acts
              .map(a => `Act ${a.actIndex + 1}`)
              .join(", ")
        }),

        imageContainer,
        togglePrompt,
        promptSection,
        regenerateButton

      ]);

      return card;

    }

    // Rebuilds the visible asset grid based on the currently selected tab.
    function renderAssets() {
      assetGrid.innerHTML = "";

      const assets =
        currentView === "backgrounds"
          ? backgroundAssets
          : characterAssets;

      assets.forEach(asset => {
        assetGrid.appendChild(
          renderAssetCard(asset)
        );
      });

    }

    bgTab.addEventListener("click", () => {
      currentView = "backgrounds";

      bgTab.classList.add("active");
      charTab.classList.remove("active");

      renderAssets();
    });

    charTab.addEventListener("click", () => {
      currentView = "characters";

      charTab.classList.add("active");
      bgTab.classList.remove("active");

      renderAssets();
    });

    renderAssets();

    return el("div", { class: "step1-page step5b-page" }, [
      el("div", {
        class: "card"
      }, [
        el("h1", {
          text: "Step 5b — Generated Assets"
        }),

        el("div", {
          class: "small",
          text: "Review your generated backgrounds and characters. You will be able to edit prompts and regenerate each image individually."
        }),

        status,

        tabs,

        assetGrid,

        el("div", { class: "actions" }, [
          el("button", {
            class: "back-button primary-button",
            type: "button",
            text: "← Back to asset review",
            onclick: () => setViewWithHome(viewStep5aReview())
          })
        ]),

        el("button", {
          class: "next-top primary-button",
          type: "button",
          text: "Next → Overview",
          onclick: () => setViewWithHome(viewStep6Overview())
        })
      ])
    ]);
  }

  // =====================================================
  // STEP 6
  // =====================================================

  //Renders the Step 6 overview interface with story, narration, and asset review tabs.
  function viewStep6Overview() {
    const backgroundAssets = getBackgroundAssets();
    const characterAssets = getCharacterAssets();

    let currentView = "story";

    //Creates the tab buttons for the Step 6 overview views.
    const tabs = el("div", {
      class: "tabs"
    });

    const storyTab = el("button", {
      class: "tab-button active",
      type: "button",
      text: "Full Story"
    });

    const narrationTab = el("button", {
      class: "tab-button",
      type: "button",
      text: "Narration Script"
    });

    const bgTab = el("button", {
      class: "tab-button",
      type: "button",
      text: "Backgrounds"
    });

    const charTab = el("button", {
      class: "tab-button",
      type: "button",
      text: "Characters"
    });

    tabs.append(
      storyTab,
      narrationTab,
      bgTab,
      charTab
    );

    const tabContent = el("div");

    //Adds the buttons used to download the story and narration as PDFs.
    const downloadStoryBtn = el("button", {
      class: "secondary primary-button",
      type: "button",
      text: "Download Full Story PDF"
    });

    const storyBox = el("textarea", {
      class: "mono",
      style: "min-height:300px;"
    });

    storyBox.value = state.fairytaleText || "";

    storyBox.addEventListener("input", () => {
      state.fairytaleText = storyBox.value;
    });

    const genNarrBtn = el("button", {
      class: "secondary primary-button",
      type: "button",
      text: "Regenerate Narration Script"
    });

    const downloadNarrationBtn = el("button", {
      class: "secondary primary-button",
      type: "button",
      text: "Download Narration PDF"
    });

    const narrBox = el("textarea", {
      class: "mono",
      style: "min-height:260px;"
    });

    narrBox.value = state.narrationText || "";

    narrBox.addEventListener("input", () => {
      state.narrationText = narrBox.value;
    });

    //Builds and saves a text document as a PDF with simple formatting.
    function downloadTextAsPdf({
      text,
      title,
      filename,
      subtitle = ""
    }) {
      const cleanText = String(text || "").trim();

      if (!cleanText) {
        alert(
          `The ${title.toLowerCase()} is empty. Please generate or enter some text before downloading it.`
        );
        return;
      }

      if (!window.jspdf?.jsPDF) {
        alert(
          "The PDF library could not be loaded. Please check your internet connection and reload the page."
        );
        return;
      }

      const { jsPDF } = window.jspdf;

      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4"
      });

      const pageWidth =
        pdf.internal.pageSize.getWidth();

      const pageHeight =
        pdf.internal.pageSize.getHeight();

      const marginLeft = 20;
      const marginRight = 20;
      const marginTop = 20;
      const marginBottom = 20;

      const usableWidth =
        pageWidth -
        marginLeft -
        marginRight;

      const lineHeight = 6;

      let currentY = marginTop;

      function addNewPage() {
        pdf.addPage();
        currentY = marginTop;
      }

      function ensureSpace(requiredHeight = lineHeight) {
        if (
          currentY + requiredHeight >
          pageHeight - marginBottom
        ) {
          addNewPage();
        }
      }

      //PDF title
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(18);

      pdf.text(
        title,
        pageWidth / 2,
        currentY,
        {
          align: "center"
        }
      );

      currentY += 10;

      //Optional subtitle
      if (subtitle) {
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(10);
        pdf.setTextColor(100);

        const subtitleLines =
          pdf.splitTextToSize(
            subtitle,
            usableWidth
          );

        subtitleLines.forEach((line) => {
          ensureSpace(lineHeight);

          pdf.text(
            line,
            pageWidth / 2,
            currentY,
            {
              align: "center"
            }
          );

          currentY += 5;
        });

        currentY += 5;
      }

      pdf.setTextColor(0);
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);

      const paragraphs =
        cleanText.split(/\n/);

      paragraphs.forEach((paragraph) => {
        const paragraphText =
          paragraph.trim();

        if (!paragraphText) {
          ensureSpace(lineHeight);
          currentY += lineHeight;
          return;
        }

        const wrappedLines =
          pdf.splitTextToSize(
            paragraphText,
            usableWidth
          );

        wrappedLines.forEach((line) => {
          ensureSpace(lineHeight);

          pdf.text(
            line,
            marginLeft,
            currentY
          );

          currentY += lineHeight;
        });

        currentY += 2;
      });

      pdf.save(filename);
    }

    //Saves the current full story text from the editor as a PDF.
    function downloadFullStoryPdf() {
      //Saves any manual edits made in the text area
      state.fairytaleText =
        storyBox.value.trim();

      downloadTextAsPdf({
        text: state.fairytaleText,
        title: "Full Story",
        filename: "full-story.pdf",
        subtitle:
          state.storyline?.logline || ""
      });
    }

    //Saves the current narration script text from the editor as a PDF.
    function downloadNarrationPdf() {
      //Saves any manual edits made in the textarea
      state.narrationText =
        narrBox.value.trim();

      const childAge =
        state.formData?.age;

      downloadTextAsPdf({
        text: state.narrationText,
        title: "Narration Script",
        filename: "narration-script.pdf",
        subtitle: childAge
          ? `Prepared for a child aged ${childAge}`
          : ""
      });
    }

    const status = el("div", {
      class: "small"
    });

    //Generates a narration script from the current story content.
    async function generateNarration() {

      try {

        genNarrBtn.disabled = true;

        status.textContent =
          "Generating narration script...";

        const data =
          await apiPost("/api/narration", {

            storyline: state.storyline,

            fairytaleText: state.fairytaleText,

            parentName: "Parent",

            childAge: state.formData?.age || ""

          });

        state.narrationText =
          data.text || "";

        narrBox.value =
          state.narrationText;

      }

      catch (e) {

        alert(e.message || e);

      }

      finally {

        genNarrBtn.disabled = false;

        status.textContent = "";

      }

    }

    genNarrBtn.addEventListener(
      "click",
      generateNarration
    );

    downloadStoryBtn.addEventListener(
      "click",
      downloadFullStoryPdf
    );

    downloadNarrationBtn.addEventListener(
      "click",
      downloadNarrationPdf
    );

    //Prepares the section that displays downloadable background assets.
    const bgSection = el("div", {
      class: "assetGrid"
    });

    //Downloads a generated background SVG as a standalone file.
    function downloadBackgroundAsSvg(
      svgText,
      filename
    ) {
      if (!svgText) {
        alert(
          "This background SVG has not been generated."
        );

        return;
      }

      const {
        svg
      } = parseSvg(
        svgText
      );

      svg.setAttribute(
        "width",
        "262mm"
      );

      svg.setAttribute(
        "height",
        "133mm"
      );

      svg.setAttribute(
        "preserveAspectRatio",
        "xMidYMid meet"
      );

      svg.setAttribute(
        "xmlns",
        "http://www.w3.org/2000/svg"
      );

      const finalSvg =
        serializeSvg(svg);

      downloadSvgText(
        finalSvg,
        filename
      );
    }

    backgroundAssets.forEach((asset, index) => {
      const generated =
        state.puppetImages[asset.key];

      const downloadBackgroundBtn =
        el("button", {
          class:
            "secondary primary-button asset-action-button",
          type: "button",
          text: "Download SVG"
        });

      downloadBackgroundBtn.disabled =
        !generated?.svgText;

      downloadBackgroundBtn.addEventListener(
        "click",
        () => {
          const currentImage =
            state.puppetImages[asset.key];

          downloadBackgroundAsSvg(
            currentImage?.svgText,
            `background-${index + 1}.svg`
          );
        }
      );

      const imageContent =
        generated?.dataUrl
          ? el("img", {
            src: generated.dataUrl,
            alt: asset.title
          })
          : el("div", {
            class: "placeholder",
            text: "Not generated"
          });

      const card = el("div", {
        class:
          "asset-card background-asset-card"
      }, [

        el("h3", {
          text: asset.title
        }),

        el("div", {
          class: "small",
          text:
            "Used in: " +
            asset.acts
              .map(
                a => `Act ${a.actIndex + 1}`
              )
              .join(", ")
        }),

        el("div", {
          class: "asset-image"
        }, [
          imageContent
        ]),

        downloadBackgroundBtn

      ]);

      bgSection.appendChild(card);
    });

    //Asks the server whether a character should use adult or chid dimensions
    async function classifyCharacterSize(
      asset
    ) {
      const choice =
        state.assetChoices?.[
        asset.key
        ];

      const result =
        await apiPost(
          "/api/character/classify-size",
          {
            name:
              asset.name ||
              asset.title ||
              asset.key,

            title:
              asset.title || "",

            prompt:
              choice?.promptText ||
              asset.prompt ||
              ""
          }
        );

      if (
        result?.sizeClass !==
        "adult" &&
        result?.sizeClass !==
        "child"
      ) {
        throw new Error(
          "The character size classification was invalid."
        );
      }

      return result.sizeClass;
    }


    //Computes the smallest rectangle that covers both input bounds.
    function getUnionBounds(
      first,
      second
    ) {
      const minX =
        Math.min(
          first.x,
          second.x
        );

      const minY =
        Math.min(
          first.y,
          second.y
        );

      const maxX =
        Math.max(
          first.x +
          first.width,

          second.x +
          second.width
        );

      const maxY =
        Math.max(
          first.y +
          first.height,

          second.y +
          second.height
        );

      return {
        x:
          minX,

        y:
          minY,

        width:
          maxX - minX,

        height:
          maxY - minY
      };
    }

    //This function prepares the final physical character file
    async function createScaledCharacterSvg(
      svgText,
      filename,
      sizeClass
    ) {
      if (!svgText) {
        throw new Error(
          "This character SVG has not been generated."
        );
      }

      const {
        svg
      } = parseSvg(
        svgText
      );

      const measurement =
        mountSvgForMeasurement(
          svg
        );

      try {
        const measuredSvg =
          measurement.svg;

        const figure =
          measuredSvg.querySelector(
            "#character-figure"
          );

        const pedestal =
          measuredSvg.querySelector(
            "#character-pedestal"
          );

        if (!figure) {
          throw new Error(
            "The character figure group was not found."
          );
        }

        if (!pedestal) {
          throw new Error(
            "The character pedestal was not found."
          );
        }

        const figureBounds =
          figure.getBBox();

        const pedestalBounds =
          pedestal.getBBox();

        if (
          figureBounds.width <= 0 ||
          figureBounds.height <= 0
        ) {
          throw new Error(
            "The character figure could not be measured."
          );
        }

        const targetFigureHeightMm =
          sizeClass === "adult"
            ? 39
            : 26;

        const combinedBounds =
          getUnionBounds(
            figureBounds,
            pedestalBounds
          );

        const paddingMm =
          0.5;

        const unitsPerMm =
          figureBounds.height /
          targetFigureHeightMm;

        const paddingUnits =
          paddingMm *
          unitsPerMm;

        const croppedBounds = {
          x:
            combinedBounds.x -
            paddingUnits,

          y:
            combinedBounds.y -
            paddingUnits,

          width:
            combinedBounds.width +
            paddingUnits * 2,

          height:
            combinedBounds.height +
            paddingUnits * 2
        };

        const physicalWidthMm =
          croppedBounds.width /
          unitsPerMm;

        const physicalHeightMm =
          croppedBounds.height /
          unitsPerMm;

        measuredSvg.setAttribute(
          "viewBox",
          [
            croppedBounds.x,
            croppedBounds.y,
            croppedBounds.width,
            croppedBounds.height
          ].join(" ")
        );

        measuredSvg.setAttribute(
          "width",
          `${physicalWidthMm}mm`
        );

        measuredSvg.setAttribute(
          "height",
          `${physicalHeightMm}mm`
        );

        measuredSvg.setAttribute(
          "preserveAspectRatio",
          "xMidYMid meet"
        );

        measuredSvg.setAttribute(
          "xmlns",
          "http://www.w3.org/2000/svg"
        );

        weldCharacterAndPedestalForExport(
          measuredSvg
        );

        const finalSvgText =
          serializeSvg(
            measuredSvg
          );

        downloadSvgText(
          finalSvgText,
          filename
        );

        return {
          sizeClass,
          targetFigureHeightMm,
          physicalWidthMm,
          physicalHeightMm
        };

      } finally {
        measurement.container.remove();
      }
    }

    const charSection = el("div", {
      class: "assetGrid"
    });

    characterAssets.forEach(
      (asset) => {
        const generated =
          state.puppetImages[
          asset.key
          ];

        const downloadCharacterBtn =
          el("button", {
            class:
              "secondary primary-button asset-action-button",

            type: "button",

            text:
              "Download Character SVG"
          });

        downloadCharacterBtn.disabled =
          !generated?.svgText;

        const classificationInfo =
          el("div", {
            class:
              "small character-size-info",

            text: ""
          });

        downloadCharacterBtn
          .addEventListener(
            "click",
            async () => {
              const originalText =
                downloadCharacterBtn
                  .textContent;

              try {
                downloadCharacterBtn
                  .disabled = true;

                downloadCharacterBtn
                  .textContent =
                  "Checking character size...";

                classificationInfo
                  .textContent =
                  "Determining whether the character is adult-sized or child-sized...";

                const sizeClass =
                  await classifyCharacterSize(
                    asset
                  );

                const targetHeight =
                  sizeClass === "adult"
                    ? "3.9 cm"
                    : "2.6 cm";

                classificationInfo
                  .textContent =
                  `${sizeClass === "adult"
                    ? "Adult-sized"
                    : "Child-sized"
                  } character — figure height: ${targetHeight}.`;

                downloadCharacterBtn
                  .textContent =
                  "Preparing download...";

                const currentImage =
                  state.puppetImages[
                  asset.key
                  ];

                const safeName =
                  makeSafeFilename(
                    asset.title ||
                    asset.name ||
                    asset.key
                  );

                await createScaledCharacterSvg(
                  currentImage?.svgText,

                  `${safeName}-${sizeClass}.svg`,

                  sizeClass
                );

              } catch (error) {
                console.error(error);

                classificationInfo
                  .textContent = "";

                alert(
                  error?.message ||
                  String(error)
                );

              } finally {
                downloadCharacterBtn.disabled =
                  !state.puppetImages[
                    asset.key
                  ]?.svgText;

                downloadCharacterBtn
                  .textContent =
                  originalText;
              }
            }
          );

        const imageContent =
          generated?.dataUrl
            ? el("img", {
              src:
                generated.dataUrl,

              alt:
                asset.title
            })
            : el("div", {
              class:
                "placeholder",

              text:
                "Not generated"
            });

        const card =
          el("div", {
            class:
              "asset-card character-asset-card"
          }, [

            el("h3", {
              text:
                asset.title
            }),

            el("div", {
              class:
                "small",

              text:
                "Used in: " +
                asset.acts
                  .map(
                    a =>
                      `Act ${a.actIndex + 1
                      }`
                  )
                  .join(", ")
            }),

            el("div", {
              class:
                "asset-image"
            }, [
              imageContent
            ]),

            classificationInfo,

            downloadCharacterBtn

          ]);

        charSection.appendChild(
          card
        );
      }
    );

    //Removes the active class from every tab and adds it to the selected one
    function activate(tab) {
      [
        storyTab,
        narrationTab,
        bgTab,
        charTab
      ].forEach(b => b.classList.remove("active"));

      tab.classList.add("active");
    }

    //Renders the currently selected Step 6 content view inside the tab area.
    function renderTab() {
      tabContent.innerHTML = "";

      switch (currentView) {

        case "story":
          tabContent.appendChild(
            el("div", {
              class: "story-toolbar download-toolbar"
            }, [
              downloadStoryBtn
            ])
          );

          tabContent.appendChild(storyBox);
          break;

        case "narration":
          tabContent.appendChild(
            el("div", {
              class: "story-toolbar narration-toolbar"
            }, [
              genNarrBtn,
              downloadNarrationBtn
            ])
          );

          tabContent.appendChild(narrBox);
          break;

        case "backgrounds":
          tabContent.appendChild(bgSection);
          break;

        case "characters":
          tabContent.appendChild(charSection);
          break;
      }
    }

    storyTab.onclick = () => {
      currentView = "story";
      activate(storyTab);
      renderTab();
    };

    narrationTab.onclick = () => {
      currentView = "narration";
      activate(narrationTab);
      renderTab();
    };

    bgTab.onclick = () => {
      currentView = "backgrounds";
      activate(bgTab);
      renderTab();
    };

    charTab.onclick = () => {
      currentView = "characters";
      activate(charTab);
      renderTab();
    };

    renderTab();

    if (!state.narrationText.trim()) {
      generateNarration();
    }

    return el("div", { class: "step1-page step5b-page" }, [
      el("div", { class: "card" }, [
        el("h1", {
          text: "Step 6 — Final Overview"
        }),

        tabs,
        tabContent,

        el("div", { class: "actions" }, [
          el("button", {
            class: "back-button primary-button",
            type: "button",
            text: "← Back to generated assets",
            onclick: () => setViewWithHome(viewStep5bDisplay())
          }),

        ]),

        status
      ])
    ]);
  }

  // =====================================================
  // START
  // =====================================================

  (async () => {
    document.body.classList.add("landing-active");                         //Activates the landing page style

    const ok = await checkComfy();                                         //Waits for the ComfyUI health check

    if (!ok) {
      alert(
        "ComfyUI Desktop does not appear to be running.\n\nPlease open ComfyUI Desktop before using the app."
      );
    }

    setView(viewLanding());                                                //Displays the landing page interface
    const homeBtn = createHomeButton();
    document.body.appendChild(homeBtn);
  })();
});